# Generated by Django 5.1.6 on 2025-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', help_text='Draft: not visible to applicants, Active: open for applications.', max_length=20),
        ),
    ]
