# Generated by Django 5.1.6 on 2025-06-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_service_id'),
        ('dynamic_form', '0003_formsubmission_org_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='dynamic_form.formsubmission', to_field='proposal_id'),
        ),
    ]
