# Generated by Django 5.1.6 on 2025-06-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_screeningresult_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
