# Generated by Django 5.1.6 on 2025-07-01 13:38

import configuration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_service_end_date_service_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=configuration.models.service_document_upload_path),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=configuration.models.service_image_upload_path),
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('stopped', 'Stopped')], default='draft', help_text='Draft: not visible to applicants, Active: open for applications.', max_length=20),
        ),
    ]
