# Generated by Django 5.1.4 on 2025-07-03 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_service_documents_service_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcommittee',
            name='is_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='screeningcommittee',
            name='sub_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_headed_committees', to=settings.AUTH_USER_MODEL),
        ),
    ]
