# Generated by Django 5.1.4 on 2025-07-03 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_service_evaluation_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('stopped', 'Stopped')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ScreeningWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_stages', models.JSONField(default=list, help_text="Ordered list of enabled stages, e.g. ['admin_screening','technical_screening','technical_evaluation','presentation']")),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config', to='configuration.service')),
            ],
        ),
    ]
