# Generated by Django 5.1.4 on 2025-07-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_alter_service_status_screeningworkflowconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AddField(
            model_name='service',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='service_documents/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
