# Generated by Django 5.1.6 on 2025-07-08 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_alter_service_name'),
        ('dynamic_form', '0006_formsubmission_based_on_ipr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='dynamic_form.formtemplate'),
        ),
    ]
