# Generated by Django 5.1.4 on 2025-07-06 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_alter_service_name'),
        ('dynamic_form', '0008_alter_formsubmission_proposed_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='dynamic_form.formtemplate'),
        ),
    ]
