# Generated by Django 5.1.6 on 2025-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='proposal_duration_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
