# Generated by Django 5.1.4 on 2025-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_proposal_duration_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="applicant_aadhar",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="applicant_passport",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="applicant_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="approval_certificate",
            field=models.FileField(blank=True, null=True, upload_to="org/approvals/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="dsir_certificate",
            field=models.FileField(blank=True, null=True, upload_to="org/dsir/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_organization_domestic",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization_registration_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="org/certificates/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="user/resumes/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="share_holding_pattern",
            field=models.FileField(
                blank=True, null=True, upload_to="org/shareholding/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="three_years_financial_report",
            field=models.FileField(blank=True, null=True, upload_to="org/financial/"),
        ),
    ]
