# Generated by Django 5.1.4 on 2025-06-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_applicant_aadhar_profile_applicant_passport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="id_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
