# Generated by Django 5.1.4 on 2025-07-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_tan_pan_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companyAsPerCfp',
            field=models.CharField(blank=True, choices=[('domestic_company', 'Domestic Company(ies) with focus on telecom R&D, Use case development'), ('startup_msme', 'Startups / MSMEs'), ('academic', 'Academic institutions'), ('rnd_section8_govt', 'R&D institutions, Section 8 companies / Societies, Central & State government entities / PSUs /Autonomous Bodies/SPVs / Limited liability partnerships')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='individualPAN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='individualPanAttachment',
            field=models.FileField(blank=True, null=True, upload_to='Applicant Pan'),
        ),
    ]
