# Generated by Django 5.1.4 on 2025-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_companyaspercfp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='individualPAN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
