# Generated by Django 5.1.6 on 2025-05-26 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveIntegerField(editable=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('not shortlisted', 'Not Shortlisted')], default='pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('evaluated_document', models.FileField(blank=True, null=True, upload_to='screening/admin_docs/')),
                ('admin_screened_at', models.DateTimeField(auto_now_add=True)),
                ('technical_evaluated', models.BooleanField(default=False)),
                ('admin_evaluated', models.BooleanField(default=False)),
                ('admin_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_screenings', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_records', to='dynamic_form.formsubmission')),
            ],
            options={
                'ordering': ['-cycle', '-admin_screened_at'],
                'unique_together': {('proposal', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='TechnicalScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_decision', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('not shortlisted', 'Not Shortlisted')], default='pending', max_length=20)),
                ('technical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('technical_remarks', models.TextField(blank=True, null=True)),
                ('technical_document', models.FileField(blank=True, null=True, upload_to='screening/technical_docs/')),
                ('technical_screened_at', models.DateTimeField(auto_now_add=True)),
                ('technical_evaluated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_record', to='screening.screeningrecord')),
                ('technical_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-technical_screened_at'],
            },
        ),
    ]
