# Generated by Django 5.1.6 on 2025-06-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalscreeningrecord',
            name='technical_document',
            field=models.FileField(blank=True, null=True, upload_to='screening/technical_screening_docs/'),
        ),
    ]
