# Generated by Django 5.1.6 on 2025-05-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_required', models.PositiveIntegerField()),
                ('revised_time_required', models.PositiveIntegerField()),
                ('grant_from_ttdf', models.PositiveIntegerField()),
                ('initial_contri_applicant', models.PositiveIntegerField()),
                ('revised_contri_applicant', models.PositiveIntegerField()),
                ('initial_grant_from_ttdf', models.PositiveIntegerField()),
                ('revised_grant_from_ttdf', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('agreement', models.FileField(blank=True, null=True, upload_to='milestones/agreements/')),
                ('mou_document', models.FileField(blank=True, null=True, upload_to='milestones/mou/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='dynamic_form.formsubmission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_milestones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='milestones/finance/')),
                ('status', models.CharField(choices=[('PENDING_IA', 'Pending IA'), ('IA_REJECTED', 'IA Rejected'), ('IA_APPROVED', 'IA Approved')], default='PENDING_IA', max_length=20)),
                ('ia_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_requests', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests', to='dynamic_form.formsubmission', to_field='proposal_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_finance_requests', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests', to='milestones.milestone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpr', models.FileField(blank=True, null=True, upload_to='milestones/mpr/')),
                ('mpr_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('mcr', models.FileField(blank=True, null=True, upload_to='milestones/mcr/')),
                ('mcr_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uc', models.FileField(blank=True, null=True, upload_to='milestones/uc/')),
                ('uc_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('assets', models.FileField(blank=True, null=True, upload_to='milestones/assets/')),
                ('assets_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='milestones.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='milestones.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_JF', 'Pending JF'), ('JF_REJECTED', 'JF Rejected'), ('JF_APPROVED', 'JF Approved')], default='PENDING_JF', max_length=20)),
                ('jf_remark', models.TextField(blank=True, null=True)),
                ('advance_payment', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ld', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('adjustment_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('net_claim_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ia_action', models.CharField(choices=[('PENDING_IA', 'Pending IA'), ('ACCEPTED', 'Accepted by IA'), ('REJECTED', 'Rejected by IA')], default='PENDING_IA', max_length=20)),
                ('ia_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_claim', to='milestones.financerequest')),
                ('ia_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_claims', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='milestones.milestone')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='dynamic_form.formsubmission', to_field='proposal_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_date', models.DateField()),
                ('sanction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sanction_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_JF', 'Pending JF'), ('JF_REJECTED', 'JF Rejected'), ('JF_APPROVED', 'JF Approved')], default='PENDING_JF', max_length=20)),
                ('jf_remark', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_finance_sanctions', to=settings.AUTH_USER_MODEL)),
                ('finance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_sanctions', to='milestones.financerequest')),
                ('jf_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_finance_sanctions', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_sanctions', to='dynamic_form.formsubmission', to_field='proposal_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_finance_sanctions', to=settings.AUTH_USER_MODEL)),
                ('payment_claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_sanction', to='milestones.paymentclaim')),
            ],
            options={
                'ordering': ['-sanction_date'],
            },
        ),
        migrations.CreateModel(
            name='ProposalMouDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='proposal_mou/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mou_document', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time_required', models.PositiveIntegerField()),
                ('revised_time_required', models.PositiveIntegerField()),
                ('grant_from_ttdf', models.PositiveIntegerField()),
                ('initial_contri_applicant', models.PositiveIntegerField()),
                ('revised_contri_applicant', models.PositiveIntegerField()),
                ('initial_grant_from_ttdf', models.PositiveIntegerField()),
                ('revised_grant_from_ttdf', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_submilestones', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submilestones', to='milestones.milestone')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_submilestones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='sub_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='milestones.submilestone'),
        ),
        migrations.AddField(
            model_name='financerequest',
            name='submilestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_requests', to='milestones.submilestone'),
        ),
        migrations.CreateModel(
            name='SubMilestoneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpr', models.FileField(blank=True, null=True, upload_to='submilestones/mpr/')),
                ('mpr_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('mcr', models.FileField(blank=True, null=True, upload_to='submilestones/mcr/')),
                ('mcr_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uc', models.FileField(blank=True, null=True, upload_to='submilestones/uc/')),
                ('uc_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('assets', models.FileField(blank=True, null=True, upload_to='submilestones/assets/')),
                ('assets_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submilestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='milestones.submilestone')),
            ],
        ),
    ]
