# Generated by Django 5.1.6 on 2025-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='funds_requested',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
