# Generated by Django 5.1.6 on 2025-06-17 19:14

import milestones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_milestone_funds_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='agreement',
        ),
        migrations.AddField(
            model_name='milestone',
            name='aagreement',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_agreement),
        ),
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('on_time', 'On Time')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('delayed', 'Delayed'), ('on_time', 'On Time')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='financerequest',
            name='document',
            field=models.FileField(upload_to=milestones.models.upload_to_finance),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='mou_document',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_mou),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='assets',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_assets),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='mcr',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_mcr),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='mpr',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_mpr),
        ),
        migrations.AlterField(
            model_name='milestonedocument',
            name='uc',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_uc),
        ),
        migrations.AlterField(
            model_name='proposalmoudocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=milestones.models.upload_to_mou),
        ),
    ]
