# Generated by Django 5.1.6 on 2025-06-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_remove_milestone_agreement_milestone_aagreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='aagreement',
            new_name='agreement',
        ),
    ]
