# Generated by Django 5.1.6 on 2025-06-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0004_rename_aagreement_milestone_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='activities',
            field=models.TextField(blank=True),
        ),
    ]
