# Generated by Django 5.1.6 on 2025-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0006_remove_milestone_activities_milestone_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submilestone',
            name='activities',
            field=models.TextField(blank=True),
        ),
    ]
