# Generated by Django 5.1.4 on 2025-07-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0007_milestone_activities_submilestone_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='funds_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='initial_contri_applicant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='initial_grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='revised_contri_applicant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='revised_grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='revised_time_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='time_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='initial_contri_applicant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='initial_grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='revised_contri_applicant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='revised_grant_from_ttdf',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='revised_time_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submilestone',
            name='time_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
