# Generated by Django 5.1.6 on 2025-05-26 07:27

import django.db.models.deletion
import static_form.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(default=static_form.models.generate_form_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='static_forms/profile_images/')),
                ('highest_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_type', models.CharField(max_length=100)),
                ('registration_info', models.CharField(max_length=255)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('annual_report', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('approval_certificate', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('industry_authorisation_letter', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('share_holding_pattern_certificate', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('address', models.TextField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='static_forms/docs/')),
                ('justification', models.TextField(blank=True, null=True)),
                ('other_sources_contribution', models.TextField(blank=True, null=True)),
                ('other_sources_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_received_details', models.TextField(blank=True, null=True)),
                ('funding_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approx_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applicant_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('declaration_document', models.FileField(blank=True, null=True, upload_to='static_forms/declarations/')),
                ('proposal_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='static_forms/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_forms', to='configuration.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('document_id', models.CharField(max_length=50)),
                ('static_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='static_form.staticform')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('static_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='static_form.staticform')),
            ],
        ),
    ]
