# Generated by Django 5.1.6 on 2025-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='details_source_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='expected_source_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
