# Generated by Django 5.1.6 on 2025-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0003_formsubmission_org_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='applicationDocument',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='collaborator_mou',
            field=models.FileField(upload_to='mou/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='declaration_document',
            field=models.FileField(blank=True, null=True, upload_to='declarations/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_architecture_chart',
            field=models.FileField(blank=True, null=True, upload_to='ipr/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_patent_file',
            field=models.FileField(blank=True, null=True, upload_to='ipr/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_annual_report',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_approval_certificate',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_industry_auth_letter',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_registration_certificate_2',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_shareholding_pattern_file',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_tan_pan_cin_file',
            field=models.FileField(blank=True, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to='pan/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='passport/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='resume_upload',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
