# Generated by Django 5.1.6 on 2025-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0004_alter_formsubmission_applicationdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='individual_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
