# Generated by Django 5.1.6 on 2025-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0006_formsubmission_based_on_ipr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='alternate_technology_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='budget_other_source_2_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='budget_other_source_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='business_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='collaborator_mou',
            field=models.FileField(blank=True, null=True, upload_to='mou/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='collaborator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='collaborator_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='commercialization_potential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='commercialization_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='consortiumPartner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='cyber_security',
            field=models.TextField(blank=True, help_text="Write 'NA' if none", null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='end_to_end_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='finance_gov_t_funding',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='finance_outstanding_loan',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='inventive_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_approval_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_background_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_based_on_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_countries_jurisdiction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_dot_related',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_generate_new_ip',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_incubation',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_licensed_regulatory_approvals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_ownership_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_potential_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_previous_submission',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_proposal_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_regulatory_info',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_status_approval_proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_status_approvals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='manpower_job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='manpower_min_qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='manpower_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='national_importance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='novelty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_shares_51pct_indian_citizens',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='patent_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='patent_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='potential_competitors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='potential_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='preliminary_work_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='proposal_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='scope_of_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='significance_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='support_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='technical_feasibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='technology_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
