# Generated by Django 5.1.4 on 2025-07-05 14:39

import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0006_remove_formsubmission_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='based_on_ipr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='business_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='collaborator_mou',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'mou'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='collaborator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='collaborator_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='commercialization_potential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='consortiumPartner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contribution_applicant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contribution_expected_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contribution_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contribution_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='data_security_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='end_to_end_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='equipment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='equipment_contributor_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='equipment_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='equipment_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='equipment_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='expected_other_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_loan_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_loan_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of uploaded file paths', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fund_source_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='gantt_chart',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'gantt_charts'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='grant_from_ttdf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='grant_to_turnover_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='has_loan',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'shareholder_docs'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='ip_ownership_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='ip_proposal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manpower_details',
            field=models.JSONField(blank=True, default=list, help_text='List of manpower entries. Each entry: {jobTitle, minimumQualification, ageLimit, roleInProject, numberOfPositions, durationMonths, proposedMonthlySalary, totalCost, totalProposalMonthlySalary}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='model_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='national_importance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='other_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of other requirement entries. Each entry: {item, quantity, unitPrice, totalPrice, specifications, certification, remarks}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='other_source_funding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='potential_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='preliminary_work_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='proof_of_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='proposal_abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='proposal_brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='proposal_presentation',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'proposal_presentations'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='proposed_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_epf_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='rd_staff_resume',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'rd_staff_resumes'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='regulatory_approvals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='required_support_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='risk_factors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='share_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='status_approvals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technical_proposal',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'technical_proposals'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='technology_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='total_project_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='tsp_support_letter',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'tsp_support_letters'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='ttdf_applied_before',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='use_case',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='applicant_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20, null=True),
        ),
    ]
