# Generated by Django 5.1.6 on 2025-07-08 09:40

import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0007_alter_formsubmission_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='dpr',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'DPR'})),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Presentation'})),
        ),
    ]
