# Generated by Django 5.1.4 on 2025-07-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0007_formsubmission_based_on_ipr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='proposed_village',
            field=models.CharField(blank=True, choices=[('delhi 1', 'Delhi 1 '), ('delhi 2', 'Delhi 2'), ('delhi 3', 'Delhi3')], max_length=255, null=True),
        ),
    ]
