# Generated by Django 5.1.4 on 2025-07-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0008_alter_formsubmission_proposed_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='centralised_servers_and_edge_analytics',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='civil_electrical_infrastructure',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='fixed_wireless_access',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='installation_infrastructure_and_commissioning',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='network_core',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='operation_maintenance_and_warranty',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='passive_components',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='radio_access_network',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='sensor_network_costs',
            field=models.JSONField(blank=True, default=dict, help_text='{"smartPanchayat": {"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}, "smartAgriculture": {"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}, "smartEducation": {"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}, "smartHealth": {"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0} }', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='software_components',
            field=models.JSONField(blank=True, default=dict, help_text='{"items": [{"item": "", "unit": "", "unitPrice": 0, "totalPrice": 0}], "sectionTotal": 0}', null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='total_proposal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
