# Generated by Django 5.1.6 on 2025-07-09 09:30

import django.db.models.deletion
import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0008_formsubmission_dpr_formsubmission_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='based_on_ipr',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='collaborator_mou',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='collaborator_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='collaborator_type',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='consortiumPartner',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='equipment_amount',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='equipment_contributor_type',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='equipment_item',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='equipment_quantity',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='equipment_unit_price',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='fund_loan_documents',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='ip_ownership_details',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='ip_proposal',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='proof_of_status',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_designation',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_email',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_epf_details',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_highest_qualification',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_mobile',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='rd_staff_resume',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='regulatory_approvals',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='share_holder_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='share_percentage',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='status_approvals',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_address',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_designation',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_email',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_mobile_number',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_name',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='tsp_support_letter',
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name_collab', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_name_collab', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_type_collab', models.CharField(blank=True, max_length=50, null=True)),
                ('ttdf_company', models.CharField(blank=True, choices=[('domestic_company', 'Domestic Company(ies) with focus on telecom R&D, Use case development'), ('startup_msme', 'Startups / MSMEs'), ('academic', 'Academic institutions'), ('rnd_section8_govt', 'R&D institutions, Section 8 companies / Societies, Central & State government entities / PSUs /Autonomous Bodies/SPVs / Limited liability partnerships')], max_length=30, null=True)),
                ('pan_file_collb', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'collaborator/pan'}))),
                ('pan_file_name_collab', models.CharField(blank=True, max_length=255, null=True)),
                ('mou_file_collab', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'collaborator/mou'}))),
                ('mou_file_name_collab', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contributor_type', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FundLoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'resume'}))),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_loan_documents', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='IPRDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Unique name or label for this form entry', max_length=255, null=True)),
                ('national_importance', models.TextField(blank=True, null=True)),
                ('commercialization_potential', models.TextField(blank=True, null=True)),
                ('risk_factors', models.TextField(blank=True, null=True)),
                ('preliminary_work_done', models.TextField(blank=True, null=True)),
                ('technology_status', models.TextField(blank=True, null=True)),
                ('business_strategy', models.TextField(blank=True, null=True)),
                ('based_on_ipr', models.TextField(blank=True, null=True)),
                ('ip_ownership_details', models.TextField(blank=True, null=True)),
                ('ip_proposal', models.TextField(blank=True, null=True)),
                ('regulatory_approvals', models.TextField(blank=True, null=True)),
                ('status_approvals', models.TextField(blank=True, null=True)),
                ('proof_of_status', models.TextField(blank=True, null=True)),
                ('t_name', models.CharField(blank=True, max_length=255, null=True)),
                ('t_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('t_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('t_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('t_address', models.TextField(blank=True, null=True)),
                ('t_support_letter', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'support_letters'}))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iprdetails', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='RDStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'rdstaff/resume'}))),
                ('epf_details', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdstaff', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'shareholder/docs'}))),
                ('identity_document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='dynamic_form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('share_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'subshareholder/docs'}))),
                ('identity_document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_shareholders', to='dynamic_form.formsubmission')),
            ],
        ),
    ]
