# Generated by Django 5.1.4 on 2025-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dynamic_form",
            "0009_formsubmission_centralised_servers_and_edge_analytics_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="budget_estimate",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Nested budget: {'tables':[{'id':'','title':'','serviceOfferings':[{'id':'','name':'','items':[{'id':'','description':'','financials':{'capex':{'year0':{...}},'opex':{'year1':{...}}}}]}]}]}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="income_estimate",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Nested income estimate: {'rows':[{'id':'','serviceOffering':'','year1':{'estimatedTransactions':'','userCharge':'','estimatedRevenue':''},'year2':{'estimatedTransactions':'','userCharge':'','estimatedRevenue':''}}]}",
                null=True,
            ),
        ),
    ]
