# Generated by Django 5.1.4 on 2025-07-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0010_formsubmission_budget_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='current_trl',
            field=models.PositiveIntegerField(blank=True, help_text='Can be filled later', null=True),
        ),
    ]
