# Generated by Django 5.1.6 on 2025-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0010_collaborator_collaborator_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='ttdf_company',
            field=models.CharField(blank=True, choices=[('domestic_company', 'Domestic Company(ies) with focus on telecom R&D, Use case development'), ('startup_msme', 'Startups / MSMEs'), ('academic', 'Academic institutions'), ('rnd_section8_govt', 'R&D institutions, Section 8 companies / Societies, Central & State government entities / PSUs /Autonomous Bodies/SPVs / Limited liability partnerships')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='use_case',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
