# Generated by Django 5.1.4 on 2025-07-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0011_alter_collaborator_ttdf_company_alter_equipment_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdstaff',
            old_name='resume',
            new_name='rd_staf_resume',
        ),
    ]
