# Generated by Django 5.1.4 on 2025-07-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0011_formsubmission_current_trl"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="grants_from_ttdf",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
