# Generated by Django 5.1.4 on 2025-07-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0012_formsubmission_grants_from_ttdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="org_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
