# Generated by Django 5.1.4 on 2025-07-14 10:14

import django.db.models.deletion
import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0012_rename_resume_rdstaff_rd_staf_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundloandocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Loan'})),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resumefile', models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Team Resumes/'}))),
                ('resumetext', models.TextField(blank=True, null=True)),
                ('otherdetails', models.TextField(blank=True, null=True)),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='dynamic_form.formsubmission')),
            ],
        ),
    ]
