# Generated by Django 5.1.4 on 2025-07-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0013_alter_fundloandocument_document_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="completed_sections",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of completed section indices",
                null=True,
            ),
        ),
    ]
