# Generated by Django 5.1.4 on 2025-07-15 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0014_formsubmission_completed_sections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collaborator",
            old_name="pan_file_collb",
            new_name="pan_file_collab",
        ),
    ]
