# Generated by Django 5.1.4 on 2025-07-14 17:02

import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0014_alter_iprdetails_proof_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprdetails',
            name='proof_of_status',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Proof of Status'})),
        ),
    ]
