# Generated by Django 5.1.4 on 2025-07-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0015_alter_iprdetails_proof_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprdetails',
            name='based_on_ipr',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
