# Generated by Django 5.1.4 on 2025-07-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0015_rename_pan_file_collb_collaborator_pan_file_collab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="ttdf_company",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "domestic_company",
                        "Domestic Company(ies) with focus on telecom R&D, Use case development",
                    ),
                    ("startup_msme", "Startups/MSMEs"),
                    ("academic", "Academic institutions"),
                    (
                        "rnd_section8_govt",
                        "R&D Institutions, Section 8 companies / Societies, Central & State government entities / PSUs /Autonomous Bodies/SPVs / Limited liability partnerships",
                    ),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
