# Generated by Django 5.1.4 on 2025-07-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0016_alter_iprdetails_based_on_ipr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='collaborator_type',
            new_name='applicantType',
        ),
    ]
