# Generated by Django 5.1.4 on 2025-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0017_rename_collaborator_type_collaborator_applicanttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='funds_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
