# Generated by Django 5.1.4 on 2025-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0017_alter_collaborator_ttdf_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="collaborator_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("principalApplicant", "principalApplicant"),
                    ("consortiumPartner", "consortiumPartner"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
