# Generated by Django 5.1.4 on 2025-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0019_alter_collaborator_ttdf_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="contribution_rows",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Array of contribution entries",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="fund_rows",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of fund entries", null=True
            ),
        ),
    ]
