# Generated by Django 5.1.4 on 2025-07-15 18:14

import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0021_alter_iprdetails_proof_of_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="gantt_chart",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=functools.partial(
                    dynamic_form.models.upload_to_dynamic,
                    *(),
                    **{"subfolder": "gantt_charts"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="proposal_presentation",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=functools.partial(
                    dynamic_form.models.upload_to_dynamic,
                    *(),
                    **{"subfolder": "proposal_presentations"}
                ),
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="technical_proposal",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=functools.partial(
                    dynamic_form.models.upload_to_dynamic,
                    *(),
                    **{"subfolder": "technical_proposals"}
                ),
            ),
        ),
    ]
