# Generated by Django 5.1.6 on 2025-07-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0022_alter_formsubmission_gantt_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='funds_requested',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
