# Generated by Django 5.1.4 on 2025-07-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0023_formsubmission_funds_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="actual_contribution_applicant",
            field=models.DecimalField(
                blank=True, decimal_places=5, max_digits=15, null=True
            ),
        ),
    ]
