# Generated by Django 5.1.6 on 2025-07-16 18:49

import dynamic_form.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0024_formsubmission_actual_contribution_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='mou_file_collab',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'collaborator/mou'})),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='pan_file_collab',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'collaborator/pan'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='applicationDocument',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'pdf'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='budget_estimate_sample_doc',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Sample Document'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='declaration_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='declarations/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='dpr',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'DPR'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='equipment_overhead_sample_doc',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Sample Document'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='income_estimate_sample_doc',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Sample Document'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_architecture_chart',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='ipr/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='ipr_patent_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='ipr/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_annual_report',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_approval_certificate',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_industry_auth_letter',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_registration_certificate',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_registration_certificate_2',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_shareholding_pattern_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='org_tan_pan_cin_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='org_docs/'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='pan_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'pan'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='passport_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'passport'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='presentation',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Presentation'})),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='resume_upload',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'resume'})),
        ),
        migrations.AlterField(
            model_name='fundloandocument',
            name='document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Loan'})),
        ),
        migrations.AlterField(
            model_name='iprdetails',
            name='proof_of_status',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'ipr_proof'})),
        ),
        migrations.AlterField(
            model_name='iprdetails',
            name='t_support_letter',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'support_letters'})),
        ),
        migrations.AlterField(
            model_name='rdstaff',
            name='rd_staf_resume',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'rdstaff/resume'})),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='identity_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'shareholder/docs'})),
        ),
        migrations.AlterField(
            model_name='subshareholder',
            name='identity_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'subshareholder/docs'})),
        ),
        migrations.AlterField(
            model_name='subshareholder',
            name='identity_document_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subshareholder',
            name='organization_name_subholder',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subshareholder',
            name='share_holder_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='resumefile',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=functools.partial(dynamic_form.models.upload_to_dynamic, *(), **{'subfolder': 'Team Resumes/'})),
        ),
    ]
