# Generated by Django 5.1.6 on 2025-05-26 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(blank=True, help_text='Optional video link instead of uploaded file', max_length=500, null=True)),
                ('video', models.FileField(blank=True, help_text='Video file uploaded by admin', null=True, upload_to='presentation/videos/')),
                ('document', models.FileField(blank=True, help_text='Presentation document uploaded by admin', null=True, upload_to='presentation/documents/')),
                ('presentation_date', models.DateTimeField(blank=True, help_text='Scheduled date and time for the presentation', null=True)),
                ('document_uploaded', models.BooleanField(default=False, help_text='True once video + document + date are all provided by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Marks given by evaluator (out of max presentation marks)', max_digits=5, null=True)),
                ('evaluator_remarks', models.TextField(blank=True, help_text="Evaluator's remarks and feedback", null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, help_text='When evaluator submitted the evaluation', null=True)),
                ('final_decision', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('evaluated', 'Evaluated'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_remarks', models.TextField(blank=True, help_text="Admin's final remarks", null=True)),
                ('admin_evaluated_at', models.DateTimeField(blank=True, help_text='When admin made final decision', null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_admin_decisions', to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, help_text='Evaluator assigned from technical evaluation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_evaluations', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='dynamic_form.formsubmission', to_field='proposal_id')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'applicant')},
            },
        ),
    ]
