# Generated by Django 5.1.6 on 2025-05-30 22:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0003_formsubmission_org_type_and_more'),
        ('presentation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentation',
            unique_together={('proposal', 'applicant', 'evaluator')},
        ),
    ]
