# Generated by Django 5.1.6 on 2025-06-25 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0004_alter_formsubmission_applicationdocument_and_more'),
        ('presentation', '0002_alter_presentation_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='cache_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_admin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_applicant_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_can_make_final_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_document_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_evaluator_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_final_decision_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_is_evaluation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_is_ready_for_evaluation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_marks_summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='cached_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='admin_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='presentation/documents/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='document_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='evaluator_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='evaluator_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presentation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='presentation/videos/'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['cached_status', '-created_at'], name='presentatio_cached__2b568f_idx'),
        ),
    ]
