# Generated by Django 5.1.6 on 2025-06-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_form', '0005_alter_formsubmission_individual_pan'),
        ('presentation', '0003_presentation_cache_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_summary', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_cache', to='dynamic_form.formsubmission')),
            ],
        ),
    ]
